# Generated by Django 3.1.2 on 2020-10-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='picture',
            field=models.CharField(default=50, max_length=50),
            preserve_default=False,
        ),
    ]
