# Generated by Django 3.1.2 on 2020-10-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_offer', '0002_specialty_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.CharField(default=50, max_length=50),
            preserve_default=False,
        ),
    ]
