# Generated by Django 3.1.2 on 2020-10-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_offer', '0002_auto_20201027_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='posted',
            field=models.DateField(max_length=32, null=True),
        ),
    ]
