# Generated by Django 3.1.2 on 2020-10-31 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_offer', '0003_auto_20201031_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='vacancies', to='job_offer.specialty'),
        ),
    ]
